# Generated by Django 4.2.3 on 2023-07-03 11:04

from django.db import migrations, models
import multisite.models


class Migration(migrations.Migration):

    dependencies = [
        ("multisite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alias",
            name="is_canonical",
            field=models.BooleanField(
                default=None,
                editable=False,
                help_text="Does this domain name match the one in site?",
                null=True,
                validators=[multisite.models.validate_true_or_none],
                verbose_name="is canonical?",
            ),
        ),
    ]
